apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: observeai
  labels:
    app: elasticsearch
    component: logging
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - name: rest
    protocol: TCP
    port: 9200          # Service port
    targetPort: 9200    # Container port
    nodePort: 30092     # External access port
  - name: inter-node
    protocol: TCP
    port: 9300
    targetPort: 9300
