apiVersion: v1
kind: Namespace
metadata:
  name: observeai
  labels:
    name: observeai
    project: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: observeai-apps
  labels:
    name: observeai-apps
    project: sample-applications
