apiVersion: apps/v1
kind: Deployment
metadata:
  name: observeai-ui
  namespace: observeai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observeai-ui
  template:
    metadata:
      labels:
        app: observeai-ui
    spec:
      containers:
        - name: ui
          image: codewithaiyan/observeai-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
